-- FIXME: Currently schema name is fixed !
CREATE TABLE glf_schema.new_hire("NAME" VARCHAR(50) NOT NULL PRIMARY KEY, 
	"HIREDATA" VARCHAR(50) NOT NULL, 
	"CDATE" TIMESTAMP WITH TIME ZONE, 
	"MDATE" TIMESTAMP WITH TIME ZONE
	);
