-- FIXME: Currently schema name is fixed !
CREATE TABLE glf_schema.new_hire(NAME VARCHAR(50) NOT NULL PRIMARY KEY, 
	HIREDATE VARCHAR(50) NOT NULL, 
	CDATE TIMESTAMP WITH TIME ZONE NOT NULL, 
	MDATE TIMESTAMP WITH TIME ZONE NOT NULL
	);
